added if step to checks

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -7,9 +7,13 @@ jobs:
     steps:
       - name: step 1
         run: sleep 20
+      - name: Step 2
+        id: step-2
+        run: exit 1
       - name: Runs on Failure
-        if: failure()
-        run: echo 'Runs only on failure'
+        #if: failure()
+        if: failure() && steps.step-2.conclusion == 'failure'
+        run: echo 'Step 2 has failed'
       - name: Runs on Success
         if: success()
         run: echo 'Run on Success'
